apiVersion: v2
name: backstage
description: A Helm chart for Backstage - Internal Developer Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - backstage
  - developer-platform
  - idp
home: https://backstage.io
sources:
  - https://github.com/backstage/backstage
maintainers:
  - name: Platform Team
    email: platform@company.com
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.10.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled 