apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    name: backstage
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: internal-developer-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: internal-developer-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: internal-developer-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    app.kubernetes.io/name: development
    app.kubernetes.io/part-of: internal-developer-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
    app.kubernetes.io/name: staging
    app.kubernetes.io/part-of: internal-developer-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    app.kubernetes.io/name: production
    app.kubernetes.io/part-of: internal-developer-platform 