apiVersion: v2
name: nodejs-service
description: A Helm chart for Node.js microservices
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nodejs
  - microservice
  - api
home: https://nodejs.org
sources:
  - https://github.com/nodejs/node
maintainers:
  - name: Platform Team
    email: platform@company.com
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.10.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled 