apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: internal-developer-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/internal-developer-platform
    targetRevision: HEAD
    path: helm-charts/backstage
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: ingress.hosts[0].host
          value: backstage.company.com
        - name: postgresql.auth.password
          value: ${POSTGRESQL_PASSWORD}
        - name: redis.auth.password
          value: ${REDIS_PASSWORD}
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10 